src/wml/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from workorder.views import Home


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include("auth.urls")),
    url(r'^', include("workorder.urls")),
    url(r'^$', Home, name="home"),
]




if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/workorder/urls.py
from django.conf.urls import url, include
from .views import (
	workorder_list,
	WorkOrderCreate,
	EmployeeList,
	EmployeeCreate,
	CustomerList,
	CustomerCreate,
	WorkOrderDetail,
	PurchaseList,
	PurchaseCreate,
	TaskCreate,
	TimeCardList,
	TimeCardCreate,
	DocumentationList,
	DocumentationCreate,
	document_update,
	timecard_update,
	customer_update,
	employee_update,
	workorder_update,
	purchase_update,
	InvoiceList,
	invoice_update,
	PreferenceDetails,
	invoice_approved,
	invoice_paid,
	invoice_sent,
	timecard_approved,
	purchase_approved,
	workorder_delete,
	employee_delete,
	customer_delete,
	purchase_delete,
	timecard_delete,
	documentation_delete,
	update_markup_percentage,
	update_markup_amount,
	time_card_update_markup_percentage,
	time_card_update_markup_amount,
	workorder_status_update,
	workorder_description_update,
	purchase_promised_delivery_date_update,
	QuoteList,
	QuoteCreate,
	quote_delete,
	quote_update,
	quote_status_update


	)


urlpatterns = [
    url(r'^workorder/list/$', workorder_list, name="workorder_list"),
    url(r'^workorder/create/$', WorkOrderCreate.as_view(), name="workorder_create"),
    url(r'^employee/list/$', EmployeeList.as_view(), name="employee_list"),
    url(r'^employee/create/$', EmployeeCreate.as_view(), name="employee_create"),
    url(r'^customer/list/$', CustomerList.as_view(), name="customer_list"),
    url(r'^customer/create/$', CustomerCreate.as_view(), name="customer_create"),
    url(r'^workorder/detail/(?P<pk>[\d]+)/$', WorkOrderDetail.as_view(), name='workorder_detail'),
    url(r'^purchase/list/$', PurchaseList.as_view(), name="purchase_list"),
    url(r'^purchase/create/$', PurchaseCreate, name="purchase_create"),
    url(r'^task/create/$', TaskCreate.as_view(), name="task_create"),
    url(r'^timecard/list/$', TimeCardList.as_view(), name="timecard_list"),
    url(r'^timecard/create/$', TimeCardCreate.as_view(), name="timecard_create"),
    url(r'^documentation/list/$', DocumentationList.as_view(), name="documentation_list"),
    url(r'^documentation/create/$', DocumentationCreate.as_view(), name="documentation_create"),
    url(r'^documentation/update/(?P<pk>[\d]+)/$', document_update, name='document_update'),
    url(r'^timecard/update/(?P<pk>[\d]+)/$', timecard_update, name='timecard_update'),
    url(r'^customer/update/(?P<pk>[\d]+)/$', customer_update, name='customer_update'),
    url(r'^employee/update/(?P<pk>[\d]+)/$', employee_update, name='employee_update'),
    url(r'^workorder/update/(?P<pk>[\d]+)/$', workorder_update, name='workorder_update'),
    url(r'^purchase/update/(?P<pk>[\d]+)/$', purchase_update, name='purchase_update'),
    url(r'^invoice/list/$', InvoiceList.as_view(), name="invoice_list"),
    url(r'^invoice/update/(?P<pk>[\d]+)/$', invoice_update, name='invoice_update'),
    url(r'^preference/(?P<pk>[\d]+)/update/$', PreferenceDetails.as_view(), name='preference_update'),
    url(r'^invoice/(?P<id>[\d]+)/approved/$', invoice_approved, name='invoice_approved'),
    url(r'^invoice/(?P<id>[\d]+)/paid/$', invoice_paid, name='invoice_paid'),
    url(r'^invoice/(?P<id>[\d]+)/sent/$', invoice_sent, name='invoice_sent'),
    url(r'^timecard/(?P<id>[\d]+)/approved/$', timecard_approved, name='timecard_approved'),
    url(r'^purchase/(?P<id>[\d]+)/approved/$', purchase_approved, name='purchase_approved'),

    url(r'^quote_status/(?P<id>[\d]+)/update/$', quote_status_update, name='quote_status_update'),
    url(r'^workorder_status/(?P<id>[\d]+)/update/$', workorder_status_update, name='workorder_status_update'),
    url(r'^workorder_description/(?P<id>[\d]+)/update/$', workorder_description_update, name='workorder_description_update'),
    url(r'^purchase/promised_delivery_date/(?P<id>[\d]+)/update/$', purchase_promised_delivery_date_update, name='purchase_promised_delivery_date_update'),

    url(r'^workorder/(?P<id>[\d]+)/delete/$', workorder_delete, name='workorder_delete'),
    url(r'^employee/(?P<id>[\d]+)/delete/$', employee_delete, name='employee_delete'),
    url(r'^customer/(?P<id>[\d]+)/delete/$', customer_delete, name='customer_delete'),
    url(r'^purchase/(?P<id>[\d]+)/delete/$', purchase_delete, name='purchase_delete'),
    url(r'^timecard/(?P<id>[\d]+)/delete/$', timecard_delete, name='timecard_delete'),
    url(r'^documentation/(?P<id>[\d]+)/delete/$', documentation_delete, name='documentation_delete'),
    url(r'^update/markup/percentage/(?P<item_id>[\d]+)/(?P<pvalue>\d+\.\d+|\d+)/$', update_markup_percentage, name='update_markup_percentage'),
    url(r'^update/markup/amount/(?P<item_id>[\d]+)/(?P<avalue>\d+\.\d+|\d+)/$', update_markup_amount, name='update_markup_amount'),
    url(r'^timecard/update/markup/percentage/(?P<time_id>[\d]+)/(?P<pvalue>\d+\.\d+|\d+)/$', time_card_update_markup_percentage, name='time_card_update_markup_percentage'),
    url(r'^timecard/update/markup/amount/(?P<time_id>[\d]+)/(?P<tavalue>\d+\.\d+|\d+)/$', time_card_update_markup_amount, name='time_card_update_markup_amount'),
    url(r'^quote/list/$', QuoteList.as_view(), name="quote_list"),
    url(r'^quote/create/$', QuoteCreate.as_view(), name="quote_create"),
    url(r'^quote/(?P<id>[\d]+)/delete/$', quote_delete, name='quote_delete'),
    url(r'^quote/update/(?P<pk>[\d]+)/$', quote_update, name='quote_update'),





]

src/workorder/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import pre_save, post_save
from datetime import datetime, timedelta
from django.utils import timezone
# Create your models here.
import inspect

def current_user():
	for frame_record in inspect.stack():
		if frame_record[3]=='get_response':
			request = frame_record[0].f_locals['request']
			break
		else:
			request = None
	return request.user

JOB_STATUS = (
	("In Progress","In Progress"),
	("Quoting","Quoting"),
	("New Job","New Job"),
	("Completed","Completed"),
	("Invoicing","Invoicing"),
	("Closed","Closed")
	)

TASK_STATUS = (
	("Not Started","Not Started"),
	("Waiting for Parts","Waiting for Parts"),
	("Waiting for Labour","Waiting for Labour"),
	("Completed","Completed"),
	("In Progress","In Progress"),
	("On-Hold","On-Hold")
	)

PO_STATUS = (
	("Closed","Closed"),
	("New","New"),
	("Order Sent","Order Sent"),
	("Waiting Receipts","Waiting Receipts"),
	("Fully Receipted","Fully Receipted")
	)

INVOICE_STATUS = (
	("Sent","Sent"),
	("Paid","Paid")
	)

QUOTE_STATUS = (
	("Quoting","Quoting"),
	("Quote Sent","Quote Sent"),
	("Approved","Approved"),
	("Rejected","Rejected")
	)


class DocumentationCategory(models.Model):
	title = models.CharField(max_length=100)
	def __str__(self):
		return self.title

class Customer(models.Model):
	customer_name 	  = models.CharField(max_length = 100)
	customer_abn 	  = models.IntegerField(null=True, blank=True)
	customer_contact  = models.CharField(max_length = 50)
	customer_email 	  = models.EmailField(max_length=254)
	customer_address  = models.TextField()
	customer_number   = models.IntegerField()
	customer_contact1 = models.CharField(max_length = 200, null=True, blank=True)
	customer_address1 = models.TextField(null=True, blank=True)
	customer_number1  = models.IntegerField(null=True, blank=True)
	is_vendor		  = models.BooleanField(default = False)

	def __str__(self):
		return self.customer_name


class Quote(models.Model):
	customer 				= models.ForeignKey(Customer,on_delete=models.CASCADE)
	description 			= models.TextField()
	custom_quote 			= models.CharField(max_length=100, unique=True)
	description_long_text 	= models.TextField()
	customer_contact_date 	= models.DateTimeField()
	quote_request_date 		= models.DateTimeField()
	promised_delivery_date  = models.DateTimeField()
	quote_sent_date 		= models.DateTimeField(null=True,blank=True)
	created_date 			= models.DateTimeField(auto_now = True,auto_now_add = False)
	modified_date 			= models.DateTimeField(auto_now = False,auto_now_add = True)
	quote_amount            = models.FloatField(default=0)
	quote_status            = models.CharField(max_length=100, choices=QUOTE_STATUS, default="Quoting")

	def __str__(self):
		return self.description

class QuoteDocument(models.Model):
	quote = models.ForeignKey(Quote,on_delete=models.CASCADE)
	category = models.ForeignKey(DocumentationCategory, on_delete=models.CASCADE)
	document   = models.FileField(upload_to = "quote_documentation")

	def __str__(self):
		return "%s"%(self.id)


def quot_status_change_receiver(sender, instance, *args, **kwargs):
	status = instance.quote_status
	if status == "Quote Sent":
		if not instance.quote_sent_date:
			instance.quote_sent_date = timezone.now()
	if status == "Approved":
		try:
			work_order = instance.workorder
		except Exception as e:
			work_order = None
		if not work_order:
			WorkOrder.objects.create(
			customer = instance.customer,
			description = instance.description,
			description_long_text = instance.description_long_text,
			quote = instance,
			customer_contact_date = instance.customer_contact_date,
			promised_delivery_date = instance.promised_delivery_date,
			quote_sent_date = instance.quote_sent_date
			)

pre_save.connect(quot_status_change_receiver, sender=Quote)



class WorkOrder(models.Model):
	customer 				= models.ForeignKey(Customer,on_delete=models.CASCADE)
	description 			= models.TextField()
	description_long_text 	= models.TextField(null=True,blank=True)
	initial_deu_date 		= models.DateTimeField(null=True,blank=True)
	quote 					= models.OneToOneField(Quote, null=True, blank=True)
	custom_quote 			= models.CharField(max_length=100,unique=True)
	customer_contact_date 	= models.DateTimeField()
	quote_sent_date 		= models.DateTimeField()
	revision 				= models.FloatField(default=1.0)
	promised_delivery_date  = models.DateTimeField()
	created_by 				= models.ForeignKey(User,on_delete=models.CASCADE,related_name='created_by',null=True,blank=True)
	created_date 			= models.DateTimeField(auto_now = True,auto_now_add = False)
	modified_by 			= models.ForeignKey(User,on_delete=models.CASCADE,related_name='modified_by',null=True,blank=True)
	modified_date 			= models.DateTimeField(auto_now = False,auto_now_add = True)
	job_status 				= models.CharField(max_length=100, choices=JOB_STATUS, default="Quoting")
	all_tasks_complete 		= models.BooleanField(default = False)
	is_template 			= models.BooleanField(default = False)


	def __str__(self):
		return self.description






class Documentation(models.Model):
	work_order = models.ForeignKey(WorkOrder,on_delete=models.CASCADE)
	category = models.ForeignKey(DocumentationCategory, on_delete=models.CASCADE, blank=True,null=True)
	document   = models.FileField(upload_to = "documentation", blank=True,null=True)

	def __str__(self):
		return "%s"%(self.id)







class Employee(models.Model):
	user                           = models.OneToOneField(User,null=True,blank=True, related_name="em_user")
	external_system 			   = models.PositiveIntegerField(null=True,blank=True)
	name  						   = models.CharField(max_length=100)
	email 	                       = models.EmailField(null=True,blank=True)
	start_date 					   = models.DateTimeField(null=True,blank=True)
	terminate_date 				   = models.DateTimeField(null=True,blank=True)
	terminated 					   = models.BooleanField(default=False)
	photo 						   = models.ImageField(upload_to="employee",null=True,blank=True)
	address 					   = models.TextField(null=True,blank=True)
	phone_number 				   = models.IntegerField(null=True,blank=True)
	emergency_contact 			   = models.CharField(max_length = 50, null=True,blank=True)
	emergency_contact_relationship = models.CharField(max_length = 50, null=True,blank=True)
	emergency_contact_number 	   = models.IntegerField(null=True,blank=True)
	emergency_contact_email 	   = models.EmailField(null=True,blank=True)
	cost_rate 					   = models.FloatField(default=0)
	chargeout_rate 				   = models.FloatField(default=0)

	def __str__(self):
		return self.name


def terminated_receiver(sender, instance, *args, **kwargs):
	if instance.terminate_date:
		instance.terminated = True
	else:
		instance.terminated = False

pre_save.connect(terminated_receiver, sender=Employee)


class Task(models.Model):
	work_order 		 = models.ForeignKey(WorkOrder,on_delete=models.CASCADE)
	task_description = models.TextField(null=True,blank=True)
	start_date       = models.DateTimeField(null=True,blank=True)
	end_date         = models.DateTimeField(null=True,blank=True)
	task_status 	 = models.CharField(max_length=100, choices=TASK_STATUS, default="In Progress")
	task_duration 	 = models.IntegerField(default=0)
	task_assigned_to = models.ManyToManyField(Employee, blank=True)
	task_due_date 	 = models.DateTimeField(null=True,blank=True)

	def __str__(self):
		return self.task_description

def task_duration_receiver(sender, instance, *args, **kwargs):
    day_between = instance.end_date-instance.start_date
    passed_hour = day_between.days * 24 + day_between.seconds // 3600
    instance.task_duration = int(passed_hour)

pre_save.connect(task_duration_receiver, sender=Task)


class TimeCard(models.Model):
	work_order 	  = models.ForeignKey(WorkOrder,on_delete=models.CASCADE)
	employee_name = models.ForeignKey(Employee,on_delete=models.CASCADE)
	start_time 	  = models.DateTimeField()
	end_time      = models.DateTimeField()
	duration      = models.FloatField(default=0)
	approved      = models.BooleanField(default = False)
	approved_date = models.DateTimeField(null=True,blank=True)

	gst = models.FloatField(default=0)
	total_cost = models.FloatField(default=0)
	mp = models.FloatField(default=0)
	ma = models.FloatField(default=0)

	def __str__(self):
		return self.employee_name.name

	def get_total_ex_gst(self):
		duration = self.duration
		chargeout_rate = self.employee_name.chargeout_rate
		markup_percentage = self.mp
		markup_amount = self.ma
		line_total_ex_gst = duration * chargeout_rate * (1+markup_percentage/100) + markup_amount
		return line_total_ex_gst

class Purchase(models.Model):
	work_order 				= models.ForeignKey(WorkOrder,on_delete=models.CASCADE,null=True,blank=True)
	po_status 			  	= models.CharField(max_length=100, choices=PO_STATUS, default="New")
	vendor					= models.ForeignKey(Customer,on_delete=models.CASCADE)
	po_cost 				= models.FloatField(default=0)
	ordered_date 		 	= models.DateTimeField(auto_now = True,auto_now_add = False)
	required_date 		 	= models.DateTimeField()
	promised_delivery_date	= models.DateTimeField(null=True,blank=True)
	approved 			  	= models.BooleanField(default=False)

	def __str__(self):
		return self.work_order.description




class Item(models.Model):
	purchase 	= models.ForeignKey(Purchase,on_delete=models.CASCADE)
	line_text = models.CharField(max_length=200)
	quantity = models.PositiveIntegerField(default=1)
	received_qty = models.PositiveIntegerField(default=1,null=True,blank=True)
	received_date = models.DateTimeField(null=True,blank=True)
	po_cost_ex_gst = models.FloatField(default=0)
	gst = models.FloatField(default=0)
	line_cost 	= models.FloatField(default=0)
	approved = models.BooleanField(default=False)
	mp = models.FloatField(default=0)
	ma = models.FloatField(default=0)
	is_markuped = models.BooleanField(default=False)

	def __str__(self):
		return self.line_text

	def get_total_ex_gst(self):
		qty = self.quantity
		cost = self.po_cost_ex_gst

src/templates/workorder/workorder_list.html
{% extends 'base.html' %}
{% load widget_tweaks %}


{% block content %}


		<div class="content-header">
			<div class="d-flex align-items-center">
				<div class="mr-auto">
					<h3 class="page-title">Work Order List</h3>
					<div class="d-inline-block align-items-center">
						<nav>
							<ol class="breadcrumb">
								<li class="breadcrumb-item"><a href="#"><i class="fa fa-home"></i></a></li>
								<li class="breadcrumb-item" aria-current="page">Work Order</li>
								<li class="breadcrumb-item active" aria-current="page">Work Order List</li>
							</ol>
						</nav>
					</div>
				</div>
				<div class="right-title">
				</div>
			</div>
		</div>


	{% if perms.workorder.add_workorder or perms.workorder.change_workorder or perms.workorder.delete_workorder %}





<section class="content">

		  <div class="row">
			<div class="col-xl-4 col-md-6 col-12 ">
				<div class="box box-inverse box-success">
				  <div class="box-body">
					<div class="flexbox">

					</div>

					<div class="text-center my-2">
					  <div class="font-size-60"><a href="/?open_work_order">{{ open_order }}</a></div>
					  <span>Open Work Orders</span>
					</div>
				  </div>
				</div>
			</div>
			<!-- /.col -->
			<div class="col-xl-4 col-md-6 col-12 ">
				<div class="box box-inverse box-primary">
				  <div class="box-body">
					<div class="flexbox">

					</div>

					<div class="text-center my-2">
					  <div class="font-size-60"><a href="/?work_orders_due_this_week">{{ deu_date }}</a></div>
					  <span>Work Orders Due This week</span>
					</div>
				  </div>
				</div>
			</div>
			<!-- /.col -->

			<div class="col-xl-4 col-md-6 col-12">
				<div class="box box-inverse box-danger">
				  <div class="box-body">
					<div class="flexbox">

					</div>

					<div class="text-center my-2">
					  <div class="font-size-60"><a href="/?work_orders_overdue">{{ overdeu_date }}<a/></div>
					  <span>Work Orders Overdue</span>
					</div>
				  </div>

				</div>
			</div>
			<!-- /.col -->
<!-- 			<div class="col-xl-3 col-md-6 col-12">
				<div class="box box-inverse box-warning">
				  <div class="box-body">
					<div class="flexbox">
					  <h5>Pending Invoice</h5>
					</div>

					<div class="text-center my-2">
					  <div class="font-size-60">00</div>
					  <span>Pending</span>
					</div>
				  </div>
				</div>
			</div> -->
			<!-- /.col -->

		  </div>

		  <div class="row">
				<div class="col-12">
					<div class="box">
						<div class="box-header with-border">
						<div class="pull-right">
							<button type="button" data-toggle="modal" data-target="#myModal" class="btn btn-info">Create Work Order</button>
						</div>
							<h4 class="box-title">Work Order List</h4>
							<h6 class="box-subtitle">Export Work Order List to Copy, CSV, Excel, PDF & Print</h6>
						</div>
						<div class="box-body" id="refreshid">
							<div class="table-responsive">

								<table id="example" class="table table-lg invoice-archive table-hover">
									<thead>
										<tr>
											<th>#Id</th>
											<th>Description</th>
											<th>Quote Sent Date</th>
											<th>Job Status</th>
											<th>Customer Contact Date</th>
											<th>Initial Deu Date</th>
											<th>Quote</th>
											<th>#Invoice</th>
											<th class="text-center">Actions</th>
										</tr>
									</thead>
									<tbody>

									{% for workorder in workorders %}
										<tr>
											<td><a id="workorder_edit" href="#" data-url = "{% url 'workorder_update' workorder.id %}">#{{ workorder.id }}</a></td>
											<td id="mainvaluetd" >
											<div id="mainvalue{{ workorder.id }}" dbid="{{ workorder.id }}" onclick="edu(this);">
												{{ workorder.description }}
											</div>
											<div id="editable{{ workorder.id }}" style="display:none;">
												<textarea id="edittext{{ workorder.id }}" class="form-control" rows="1"></textarea>
												<div class="pull-right acx" style="margin-top:5px;">
													<button type="button" data-url="{% url 'workorder_description_update' workorder.id %}" class="btn btn-info btn-xs" dbid="{{ workorder.id }}" id="add_save{{ workorder.id }}" onclick="addbtn(this)"><i class="glyphicon glyphicon-ok"></i></button>
													<button type="button" class="btn btn-info btn-xs" dbid="{{ workorder.id }}" id="edit_remove{{ workorder.id }}" onclick="removebtn(this)"><i class="glyphicon glyphicon-remove"></i></button>
												</div>
											</div>
											</td>
											<td> {{ workorder.quote_sent_date|date:"D d/m/y H:i" }}	</td>
											<td>
												<form method="post" action="">{% csrf_token %}
													<select class="form-control" id="workworder_status_dropdown_id" data-url="{% url 'workorder_status_update' workorder.id %}">
														{% for k,v in job_status %}
												   		<option value="{{ k }}" {% if workorder.job_status == k %} selected="" {% endif %} >{{ v }}</option>
													  {% endfor %}
												 </select>
												</form>
											</td>
											<td>
												{{ workorder.customer_contact_date|date:"D d/m/y H:i" }}
											</td>
											<td>
												<span class="badge badge-success"> {{ workorder.initial_deu_date|date:"D d/m/y H:i" }}</span>
											</td>
											<td>
												<h6 class="mb-0 font-weight-bold">
											{% if workorder.quote %}<a href="#" id="quote_edit" data-url = "{% url 'quote_update' workorder.quote.id %}">#{{ workorder.quote.id }}</a> {% else %}-- {% endif %}
												</h6>
											</td>
											<td>
												{% if perms.workorder.add_invoice or perms.workorder.change_invoice or perms.workorder.delete_invoice %}
												<a href="#" data-url="/invoice/update/{{workorder.invoice.id}}/" id="work_to_invoice" >#{{ workorder.invoice.id }}</a>
												{% else %}
												#{{ workorder.invoice.id }}
												{% endif %}
											</td>

											<td class="text-center">
												<div class="list-icons d-inline-flex">
													<div class="list-icons-item dropdown">
														<a href="#" class="list-icons-item dropdown-toggle" data-toggle="dropdown"><i class="fa fa-file-text"></i></a>
														<div class="dropdown-menu dropdown-menu-right">
															<a href="#" class="dropdown-item" id="workorder_edit" data-url = "{% url 'workorder_update' workorder.id %}" >
																<i class="fa fa-pencil"></i> Edit</a>
															<a href="{% url 'workorder_delete' workorder.id %}" class="dropdown-item"><i class="fa fa-remove"></i> Remove</a>
														</div>
													</div>
												</div>
											</td>
										</tr>

										{% endfor %}



									</tbody>
								</table>

							</div>
						</div>
					</div>
				</div>
			</div>
		  <!-- /.row -->

		</section>


<div class="modal fade" id="myModal">
    <div class="modal-dialog modal-lg">
      <div class="modal-content">

        <!-- Modal Header -->
        <div class="modal-header">
          <h4 class="modal-title">Create Work Order</h4>
          <button type="button" class="close" data-dismiss="modal">&times;</button>
        </div>

        <!-- Modal body -->
        <div class="modal-body">
              <div class="form-group">


      <form action="{% url 'workorder_create' %}" method="POST" id="workcreate">{% csrf_token %}
				<p id="errmsg" style="color:##f64e4e;"></p>
<div class="row">
	<div class="col-sm-6">
		<div class="form-group">
      	<label>*Customer:</label>
        {% render_field work_form.customer class="form-control" %}
    </div>
 </div>

<div class="col-sm-6">
	 <div class="form-group">
      	<label>*Description:</label>
        {% render_field work_form.description class="form-control" rows="1" %}
      </div>
</div>

</div>

<div class="row">
	<div class="col-sm-6">
	<div class="form-group">
      	<label>Long Description:</label>
        {% render_field work_form.description_long_text class="form-control" rows="1" %}
      </div>
  </div>
      <div class="col-sm-6">
      	<div class="form-group">
      	<label>*Custom Quote:</label>
        {% render_field work_form.custom_quote required="" class="form-control"  %}
      </div>

	</div>

</div>


<div class="row">
	<div class="col-sm-6">
      <div class="form-group">
      	<label>*Customer Contact Date:</label>
				<input name="customer_contact_date" class="form-control" required="" id="id_customer_contact_date" readonly="" type="text" value="{% now 'd/m/Y H:i' %}">
      </div>
	</div>
<div class="col-sm-6">
       <div class="form-group">
       	<label>*Quote Sent Date:</label>
				<input name="quote_sent_date" class="form-control" required="" id="id_quote_sent_date" readonly="" type="text"  value="{% now 'd/m/Y H:i' %}">

      </div>
</div>
</div>


<div class="row">
	<div class="col-sm-6">
 		<div class="form-group">
 		 <label>*Revision:</label>
        {% render_field work_form.revision class="form-control" %}
      </div>
    </div>

<div class="col-sm-6">
      <div class="form-group">
      	<label>*Promised Delivery Date:</label>
        {% render_field work_form.promised_delivery_date readonly="" class="form-control" required="" %}
      </div>
</div>



</div>


<div class="row">
	<div class="col-sm-6">
      <div class="form-group">
      	<label>*Job Status:</label>
        {% render_field work_form.job_status class="form-control" %}
      </div>

	</div>
</div>





<p class="top10">
	<button type="submit" class="btn btn-primary pull-right">Submit</button>
	<button type="button" class="btn btn-danger pull-right right10" data-dismiss="modal">Close</button>
</p>

      </form>

    </div>
        </div>


      </div>
    </div>
  </div>

  <div id="editcontainer"></div>

  {% else %}

  <div class="col-sm-6" style="margin-top: 30px">
	<div class="alert alert-danger">
	  <strong>Permission Denied!</strong> You do not have access this section.
	</div>
  </div>

  {% endif %}

{% endblock %}