src/wml/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from workorder.views import Home


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include("auth.urls")),
    url(r'^', include("workorder.urls")),
    url(r'^$', Home, name="home"),
]




if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/workorder/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import pre_save, post_save
from datetime import datetime, timedelta
from django.utils import timezone
# Create your models here.
import inspect

def current_user():
	for frame_record in inspect.stack():
		if frame_record[3]=='get_response':
			request = frame_record[0].f_locals['request']
			break
		else:
			request = None
	return request.user

JOB_STATUS = (
	("In Progress","In Progress"),
	("Quoting","Quoting"),
	("New Job","New Job"),
	("Completed","Completed"),
	("Invoicing","Invoicing"),
	("Closed","Closed")
	)

TASK_STATUS = (
	("Not Started","Not Started"),
	("Waiting for Parts","Waiting for Parts"),
	("Waiting for Labour","Waiting for Labour"),
	("Completed","Completed"),
	("In Progress","In Progress"),
	("On-Hold","On-Hold")
	)

PO_STATUS = (
	("Closed","Closed"),
	("New","New"),
	("Order Sent","Order Sent"),
	("Waiting Receipts","Waiting Receipts"),
	("Fully Receipted","Fully Receipted")
	)

INVOICE_STATUS = (
	("Sent","Sent"),
	("Paid","Paid")
	)

QUOTE_STATUS = (
	("Quoting","Quoting"),
	("Quote Sent","Quote Sent"),
	("Approved","Approved"),
	("Rejected","Rejected")
	)


class DocumentationCategory(models.Model):
	title = models.CharField(max_length=100)
	def __str__(self):
		return self.title

class Customer(models.Model):
	customer_name 	  = models.CharField(max_length = 100)
	customer_abn 	  = models.IntegerField(null=True, blank=True)
	customer_contact  = models.CharField(max_length = 50)
	customer_email 	  = models.EmailField(max_length=254)
	customer_address  = models.TextField()
	customer_number   = models.IntegerField()
	customer_contact1 = models.CharField(max_length = 200, null=True, blank=True)
	customer_address1 = models.TextField(null=True, blank=True)
	customer_number1  = models.IntegerField(null=True, blank=True)
	is_vendor		  = models.BooleanField(default = False)

	def __str__(self):
		return self.customer_name


class Quote(models.Model):
	customer 				= models.ForeignKey(Customer,on_delete=models.CASCADE)
	description 			= models.TextField()
	custom_quote 			= models.CharField(max_length=100, unique=True)
	description_long_text 	= models.TextField()
	customer_contact_date 	= models.DateTimeField()
	quote_request_date 		= models.DateTimeField()
	promised_delivery_date  = models.DateTimeField()
	quote_sent_date 		= models.DateTimeField(null=True,blank=True)
	created_date 			= models.DateTimeField(auto_now = True,auto_now_add = False)
	modified_date 			= models.DateTimeField(auto_now = False,auto_now_add = True)
	quote_amount            = models.FloatField(default=0)
	quote_status            = models.CharField(max_length=100, choices=QUOTE_STATUS, default="Quoting")

	def __str__(self):
		return self.description

class QuoteDocument(models.Model):
	quote = models.ForeignKey(Quote,on_delete=models.CASCADE)
	category = models.ForeignKey(DocumentationCategory, on_delete=models.CASCADE)
	document   = models.FileField(upload_to = "quote_documentation")

	def __str__(self):
		return "%s"%(self.id)


def quot_status_change_receiver(sender, instance, *args, **kwargs):
	status = instance.quote_status
	if status == "Quote Sent":
		if not instance.quote_sent_date:
			instance.quote_sent_date = timezone.now()
	if status == "Approved":
		try:
			work_order = instance.workorder
		except Exception as e:
			work_order = None
		if not work_order:
			WorkOrder.objects.create(
			customer = instance.customer,
			description = instance.description,
			description_long_text = instance.description_long_text,
			quote = instance,
			customer_contact_date = instance.customer_contact_date,
			promised_delivery_date = instance.promised_delivery_date,
			quote_sent_date = instance.quote_sent_date
			)

pre_save.connect(quot_status_change_receiver, sender=Quote)



class WorkOrder(models.Model):
	customer 				= models.ForeignKey(Customer,on_delete=models.CASCADE)
	description 			= models.TextField()
	description_long_text 	= models.TextField(null=True,blank=True)
	initial_deu_date 		= models.DateTimeField(null=True,blank=True)
	quote 					= models.OneToOneField(Quote, null=True, blank=True)
	custom_quote 			= models.CharField(max_length=100,unique=True)
	customer_contact_date 	= models.DateTimeField()
	quote_sent_date 		= models.DateTimeField()
	revision 				= models.FloatField(default=1.0)
	promised_delivery_date  = models.DateTimeField()
	created_by 				= models.ForeignKey(User,on_delete=models.CASCADE,related_name='created_by',null=True,blank=True)
	created_date 			= models.DateTimeField(auto_now = True,auto_now_add = False)
	modified_by 			= models.ForeignKey(User,on_delete=models.CASCADE,related_name='modified_by',null=True,blank=True)
	modified_date 			= models.DateTimeField(auto_now = False,auto_now_add = True)
	job_status 				= models.CharField(max_length=100, choices=JOB_STATUS, default="Quoting")
	all_tasks_complete 		= models.BooleanField(default = False)
	is_template 			= models.BooleanField(default = False)


	def __str__(self):
		return self.description






class Documentation(models.Model):
	work_order = models.ForeignKey(WorkOrder,on_delete=models.CASCADE)
	category = models.ForeignKey(DocumentationCategory, on_delete=models.CASCADE, blank=True,null=True)
	document   = models.FileField(upload_to = "documentation", blank=True,null=True)

	def __str__(self):
		return "%s"%(self.id)







class Employee(models.Model):
	user                           = models.OneToOneField(User,null=True,blank=True, related_name="em_user")
	external_system 			   = models.PositiveIntegerField(null=True,blank=True)
	name  						   = models.CharField(max_length=100)
	email 	                       = models.EmailField(null=True,blank=True)
	start_date 					   = models.DateTimeField(null=True,blank=True)
	terminate_date 				   = models.DateTimeField(null=True,blank=True)
	terminated 					   = models.BooleanField(default=False)
	photo 						   = models.ImageField(upload_to="employee",null=True,blank=True)
	address 					   = models.TextField(null=True,blank=True)
	phone_number 				   = models.IntegerField(null=True,blank=True)
	emergency_contact 			   = models.CharField(max_length = 50, null=True,blank=True)
	emergency_contact_relationship = models.CharField(max_length = 50, null=True,blank=True)
	emergency_contact_number 	   = models.IntegerField(null=True,blank=True)
	emergency_contact_email 	   = models.EmailField(null=True,blank=True)
	cost_rate 					   = models.FloatField(default=0)
	chargeout_rate 				   = models.FloatField(default=0)

	def __str__(self):
		return self.name


def terminated_receiver(sender, instance, *args, **kwargs):
	if instance.terminate_date:
		instance.terminated = True
	else:
		instance.terminated = False

pre_save.connect(terminated_receiver, sender=Employee)


class Task(models.Model):
	work_order 		 = models.ForeignKey(WorkOrder,on_delete=models.CASCADE)
	task_description = models.TextField(null=True,blank=True)
	start_date       = models.DateTimeField(null=True,blank=True)
	end_date         = models.DateTimeField(null=True,blank=True)
	task_status 	 = models.CharField(max_length=100, choices=TASK_STATUS, default="In Progress")
	task_duration 	 = models.IntegerField(default=0)
	task_assigned_to = models.ManyToManyField(Employee, blank=True)
	task_due_date 	 = models.DateTimeField(null=True,blank=True)

	def __str__(self):
		return self.task_description

def task_duration_receiver(sender, instance, *args, **kwargs):
    day_between = instance.end_date-instance.start_date
    passed_hour = day_between.days * 24 + day_between.seconds // 3600
    instance.task_duration = int(passed_hour)

pre_save.connect(task_duration_receiver, sender=Task)


class TimeCard(models.Model):
	work_order 	  = models.ForeignKey(WorkOrder,on_delete=models.CASCADE)
	employee_name = models.ForeignKey(Employee,on_delete=models.CASCADE)
	start_time 	  = models.DateTimeField()
	end_time      = models.DateTimeField()
	duration      = models.FloatField(default=0)
	approved      = models.BooleanField(default = False)
	approved_date = models.DateTimeField(null=True,blank=True)

	gst = models.FloatField(default=0)
	total_cost = models.FloatField(default=0)
	mp = models.FloatField(default=0)
	ma = models.FloatField(default=0)

	def __str__(self):
		return self.employee_name.name

	def get_total_ex_gst(self):
		duration = self.duration
		chargeout_rate = self.employee_name.chargeout_rate
		markup_percentage = self.mp
		markup_amount = self.ma
		line_total_ex_gst = duration * chargeout_rate * (1+markup_percentage/100) + markup_amount
		return line_total_ex_gst

class Purchase(models.Model):
	work_order 				= models.ForeignKey(WorkOrder,on_delete=models.CASCADE,null=True,blank=True)
	po_status 			  	= models.CharField(max_length=100, choices=PO_STATUS, default="New")
	vendor					= models.ForeignKey(Customer,on_delete=models.CASCADE)
	po_cost 				= models.FloatField(default=0)
	ordered_date 		 	= models.DateTimeField(auto_now = True,auto_now_add = False)
	required_date 		 	= models.DateTimeField()
	promised_delivery_date	= models.DateTimeField(null=True,blank=True)
	approved 			  	= models.BooleanField(default=False)

	def __str__(self):
		return self.work_order.description




class Item(models.Model):
	purchase 	= models.ForeignKey(Purchase,on_delete=models.CASCADE)
	line_text = models.CharField(max_length=200)
	quantity = models.PositiveIntegerField(default=1)
	received_qty = models.PositiveIntegerField(default=1,null=True,blank=True)
	received_date = models.DateTimeField(null=True,blank=True)
	po_cost_ex_gst = models.FloatField(default=0)
	gst = models.FloatField(default=0)
	line_cost 	= models.FloatField(default=0)
	approved = models.BooleanField(default=False)
	mp = models.FloatField(default=0)
	ma = models.FloatField(default=0)
	is_markuped = models.BooleanField(default=False)

	def __str__(self):
		return self.line_text

	def get_total_ex_gst(self):
		qty = self.quantity
		cost = self.po_cost_ex_gst

src/workorder/forms.py
from django.forms import ModelForm, inlineformset_factory, TextInput
from .models import (
	WorkOrder,
	Employee,
	Customer,
	Purchase,
	Task,
	TimeCard,
	Documentation,
	Item,
	Invoice,
	Quote,
	QuoteDocument
	)

from django import forms



class WorkOrderForm(ModelForm):
	customer_contact_date = forms.DateTimeField(input_formats=["%d/%m/%Y %H:%M"])
	quote_sent_date = forms.DateTimeField(input_formats=["%d/%m/%Y %H:%M"])
	promised_delivery_date = forms.DateTimeField(input_formats=["%d/%m/%Y %H:%M"])
	class Meta:
		model = WorkOrder
		fields = [
			"customer",
			"description",
			"description_long_text",
			"custom_quote",
			"customer_contact_date",
			"quote_sent_date",
			"revision",
			"promised_delivery_date",
			"job_status",

		]

class QuoteForm(ModelForm):
	customer_contact_date = forms.DateTimeField(input_formats=["%d/%m/%Y %H:%M"])
	# quote_sent_date = forms.DateTimeField(input_formats=["%d/%m/%Y %H:%M"])
	quote_request_date = forms.DateTimeField(input_formats=["%d/%m/%Y %H:%M"])
	promised_delivery_date = forms.DateTimeField(input_formats=["%d/%m/%Y %H:%M"])
	class Meta:
		model = Quote
		fields = [
			"customer",
			"description",
			"description_long_text",
			"customer_contact_date",
			"quote_request_date",
			"promised_delivery_date",
			"custom_quote",
			"quote_amount",
			"quote_status",

		]

class QuoteUpdateForm(ModelForm):
	customer_contact_date = forms.DateTimeField(input_formats=["%d/%m/%Y %H:%M"])
	quote_sent_date = forms.DateTimeField(input_formats=["%d/%m/%Y %H:%M"])
	quote_request_date = forms.DateTimeField(input_formats=["%d/%m/%Y %H:%M"])
	promised_delivery_date = forms.DateTimeField(input_formats=["%d/%m/%Y %H:%M"])
	class Meta:
		model = Quote
		fields = [
			"customer",
			"description",
			"description_long_text",
			"customer_contact_date",
			"quote_request_date",
			"promised_delivery_date",
			"quote_sent_date",
			"quote_amount",
			"quote_status",

		]


class EmployeeForm(ModelForm):
	start_date = forms.DateTimeField(input_formats=["%d/%m/%Y %H:%M"], required=False)
	class Meta:
		model = Employee
		fields = [
			"user",
			"external_system",
			"name",
			"email",
			"start_date",
			"photo",
			"address",
			"phone_number",
			"emergency_contact",
			"emergency_contact_relationship",
			"emergency_contact_number",
			"emergency_contact_email",
			"cost_rate",
			"chargeout_rate"
		]



class EmployeeUpdateForm(ModelForm):
	start_date = forms.DateTimeField(input_formats=["%d/%m/%Y %H:%M"], required=False)
	terminate_date = forms.DateTimeField(input_formats=["%d/%m/%Y %H:%M"], required=False)
	class Meta:
		model = Employee
		fields = [
			"user",
			"external_system",
			"name",
			"email",
			"start_date",
			'terminate_date',
			'terminated',
			"photo",
			"address",
			"phone_number",
			"emergency_contact",
			"emergency_contact_relationship",
			"emergency_contact_number",
			"emergency_contact_email",
			"cost_rate",
			"chargeout_rate"
		]


class EmployeeProfileUpdateForm(ModelForm):
	class Meta:
		model = Employee
		fields = [
			"email",
			"address",
			"phone_number",
			"emergency_contact",
			"emergency_contact_relationship",
			"emergency_contact_number",
			"emergency_contact_email",
		]


class CustomerForm(ModelForm):
	class Meta:
		model = Customer
		fields = '__all__'








class TimeCardForm(ModelForm):
	start_time = forms.DateTimeField(input_formats=["%d/%m/%Y %H:%M"])
	end_time = forms.DateTimeField(input_formats=["%d/%m/%Y %H:%M"])
	class Meta:
		model = TimeCard
		fields = ["start_time","end_time","employee_name","work_order"]








class PurchaseForm(ModelForm):
	required_date = forms.DateTimeField(input_formats=["%d/%m/%Y %H:%M"])
	promised_delivery_date = forms.DateTimeField(input_formats=["%d/%m/%Y %H:%M"], required=False)
	class Meta:
		model = Purchase
		fields = [
			"work_order",
			"po_status",
			"vendor",
			"required_date",
			"promised_delivery_date",
		]



class InvoiceForm(ModelForm):
	invoice_date = forms.DateTimeField(input_formats=["%d/%m/%Y %H:%M"])
	class Meta:
		model = Invoice
		fields = [
			"invoice_date",
			# "expected_payment_date",
			"invoice_to",
			"invoice_from_org",
			"invoice_from",
			"invoice_customer_info",
			]








class ItemInlineForm(ModelForm):
	received_date = forms.DateTimeField(input_formats=["%d/%m/%Y %H:%M"], required=False)
	class Meta:
		model = Item
		fields = [
			"purchase",
			"line_text",
			"quantity",
			"received_qty",
			"received_date",
			"po_cost_ex_gst",
			"approved",
		]

class TaskForm(ModelForm):
	start_date = forms.DateTimeField(input_formats=["%d/%m/%Y %H:%M"], required=False)
	end_date = forms.DateTimeField(input_formats=["%d/%m/%Y %H:%M"], required=False)
	task_due_date = forms.DateTimeField(input_formats=["%d/%m/%Y %H:%M"], required=False)
	class Meta:
		model = Task
		fields = [
			"work_order",
			"task_description",
			"start_date",
			"end_date",
			"task_status",
			"task_assigned_to",
			"task_due_date",
		]

class DocumentationForm(ModelForm):
	class Meta:
		model = Documentation
		fields = '__all__'


class QuoteDocumentationForm(ModelForm):
	class Meta:
		model = QuoteDocument
		fields = '__all__'

PurchaseItemInlineForm = inlineformset_factory(Purchase, Item,form=ItemInlineForm, can_delete=True, extra=0,min_num=1)
TaskItemInlineForm = inlineformset_factory(WorkOrder, Task,form=TaskForm, can_delete=True, extra=0,min_num=1)
DocumentationInlineForm = inlineformset_factory(WorkOrder, Documentation,form=DocumentationForm, can_delete=True, extra=0,min_num=1)
QuoteDocumentationInlineForm = inlineformset_factory(Quote, QuoteDocument,form=QuoteDocumentationForm, can_delete=True, extra=0,min_num=1)

src/templates/purchase/purchase_create.html
{% load widget_tweaks %}
<div class="modal fade" id="updateModal">
    <div class="modal-dialog modal-lg">
      <div class="modal-content">

        <!-- Modal Header -->
        <div class="modal-header">
          <h4 class="modal-title"> Create Purchase</h4>
          <button type="button" class="close" data-dismiss="modal">&times;</button>
        </div>

        <!-- Modal body -->
        <div class="modal-body">
              <div class="form-group">


      <form action="{% url 'purchase_create' %}" method="POST" enctype="multipart/form-data">{% csrf_token %}


<div class="row">
  <div class="col-sm-6">
    <div class="form-group">
          <label>Work Order:</label>
          {% render_field form1.work_order class="form-control" %}
      </div>
  </div>

  <div class="col-sm-6">
     <div class="form-group">
          <label>*PO Status:</label>
          {% render_field form1.po_status class="form-control" %}
        </div>
  </div>
</div>

<div class="row">
  <div class="col-sm-6">
    <div class="form-group">
          <label>*Vendor:</label>
          {% render_field form1.vendor class="form-control" %}
      </div>
  </div>
  <div class="col-sm-6">
     <div class="form-group">
          <label>*Required Date:</label>
          {% render_field form1.required_date readonly=""  class="form-control" %}
        </div>
  </div>

</div>


<div class="row">
  <div class="col-sm-6">
    <div class="form-group">
          <label>Promised Delivery Date:</label>
          {% render_field form1.promised_delivery_date readonly="" class="form-control" %}
      </div>
  </div>
</div>





<table class="table table-bordered table-sm top10">
    <thead>
		<tr>
			<th>*Line Text</th>
			<th>*QTY</th>
			<th>*Cost</th>
      <th>Received Qty</th>
      <th>Received Date</th>
			<th>Approved?</th>
			<th>Delete</th>
		</tr>
    </thead>
    <tbody>
{{ form2.management_form }}


		{% for form in form2.forms %}
			{% for hidden in form.hidden_fields %}
			    {{ hidden }}
			{% endfor %}
	<tr class="item_form_fromset">
		<td>{% render_field form.line_text class="form-control" placeholder="Line Text" required="" %}</td>
		<td>{% render_field form.quantity class="form-control" required="" %}</td>
		<td>{% render_field form.po_cost_ex_gst class="form-control" required="" %}</td>
    <td>{% render_field form.received_qty class="form-control" %}</td>
    <td>{% render_field form.received_date class="form-control" readonly="" %}</td>
		<td>{% render_field form.approved style="position: relative;left: 0;opacity: 1;margin-left: 25px;" %}</td>
		<td>{{ form.DELETE }}</td>
	</tr>

	{% endfor %}

    </tbody>
  </table>


<p class="top10">
	<button type="submit" class="btn btn-primary pull-right">Submit</button>
	<button type="button" class="btn btn-danger pull-right right10" data-dismiss="modal">Close</button>
</p>
      </form>

    </div>
        </div>

      </div>
    </div>
  </div>
<script>
  $(document).ready(function(){
    $('.item_form_fromset').formset({
      addText: 'ADD ITEMS',
      deleteText: 'DELETE',
      prefix: 'item_set',
    });



$("#id_required_date").datetimepicker({format:'d/m/Y H:i'});
$("#id_promised_delivery_date").datetimepicker({format:'d/m/Y H:i'});

$("[id$='received_date']").datetimepicker({format:'d/m/Y H:i'});

$(".add-row").click(function(){
  $("[id$='received_date']").datetimepicker({format:'d/m/Y H:i'});
  $("[id$='quantity']").last().val("1")
  $("[id$='po_cost_ex_gst']").last().val("0")
  $("[id$='received_qty']").last().val("1")

})

  });
</script>

src/templates/purchase/purchase_list.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block content %}


		<div class="content-header">
			<div class="d-flex align-items-center">
				<div class="mr-auto">
					<h3 class="page-title">Purchase Order List</h3>
					<div class="d-inline-block align-items-center">
						<nav>
							<ol class="breadcrumb">
								<li class="breadcrumb-item"><a href="#"><i class="fa fa-home"></i></a></li>
								<li class="breadcrumb-item" aria-current="page">Purchasing</li>
								<li class="breadcrumb-item active" aria-current="page">Purchase Order List
								</li>
							</ol>
						</nav>
					</div>
				</div>
				<div class="right-title">
				</div>
			</div>
		</div>

	{% if perms.workorder.add_purchase or perms.workorder.change_purchase or perms.workorder.delete_purchase %}


<section class="content">

		  <div class="row">
			<div class="col-xl-4 col-md-6 col-12 ">
				<div class="box box-inverse box-success">
				  <div class="box-body">
					<div class="flexbox">

					</div>

					<div class="text-center my-2">
					  <div class="font-size-60"> <a href="/purchase/list/?po_not_approved">{{ PO_not_approved }}</a> </div>
					  <span>PO not approved</span>
					</div>
				  </div>
				</div>
			</div>
			<!-- /.col -->
			<div class="col-xl-4 col-md-6 col-12 ">
				<div class="box box-inverse box-primary">
				  <div class="box-body">
					<div class="flexbox">
					</div>

					<div class="text-center my-2">
					  <div class="font-size-60">{{ total_qty }}</div>
					  <span>PO not Received yet</span>
					</div>
				  </div>
				</div>
			</div>
			<!-- /.col -->

			<div class="col-xl-4 col-md-6 col-12">
				<div class="box box-inverse box-danger">
				  <div class="box-body">
					<div class="flexbox">
					</div>

					<div class="text-center my-2">
					  <div class="font-size-60"><a href="/purchase/list/?po_approved">{{ PO_approved }}</a></div>
					  <span>PO is approved</span>
					</div>
				  </div>

				</div>
			</div>
			<!-- /.col -->
<!-- 			<div class="col-xl-3 col-md-6 col-12">
				<div class="box box-inverse box-warning">
				  <div class="box-body">
					<div class="flexbox">
					  <h5>Pending Invoice</h5>
					</div>

					<div class="text-center my-2">
					  <div class="font-size-60">00</div>
					  <span>Pending</span>
					</div>
				  </div>
				</div>
			</div> -->
			<!-- /.col -->

		  </div>

		  <div class="row">
				<div class="col-12">
					<div class="box">
						<div class="box-header with-border">
						<div class="pull-right">
							<!-- <a href="#" id="purchase_create" data-url="{% url 'purchase_create' %}"><i class="fa fa-plus-square-o fa-2x" aria-hidden="true"></i></a> -->
							<button type="button" id="purchase_create" data-url="{% url 'purchase_create' %}" class="btn btn-info">Create Purchase Order</button>
						</div>
							<h4 class="box-title">Purchase Order List</h4>
							<h6 class="box-subtitle">Export Purchase List to Copy, CSV, Excel, PDF & Print</h6>
						</div>
						<div class="box-body">
							<div class="table-responsive">

								<table id="example" class="table table-lg invoice-archive">
									<thead>
										<tr>
											<th>PO#</th>
											<th>PO Status</th>
											<th>Cost</th>
											<th>Vendor</th>
											<th>Promised Delivery Date</th>
											<th>Approved?</th>
											<th class="text-center">Actions</th>
										</tr>
									</thead>
									<tbody>

									{% for purchase in purchase_list %}
										<tr>
											<td><a href="#" id = "purchase_edit" data-url = "{% url 'purchase_update' purchase.id %}">#{{ purchase.id }}</a></td>
											<td>{{ purchase.po_status }}</td>
											<td>{{ purchase.po_cost|floatformat:2 }}</td>
											<td>{{ purchase.vendor.customer_name }}</td>
											<td>
												<form>{% csrf_token %}
													<input type="text" data-url="{% url 'purchase_promised_delivery_date_update' purchase.id %}" class="form-control" id="promised_delivery_date" value="{{ purchase.promised_delivery_date|date:"d/m/Y H:i" }}" style="width: 60%;"></td>
												</form/>
											<td>
											{% if purchase.approved %}
												Yes
											{% else %}
												No
											{% endif %}
											</td>
											<td class="text-center">
												<div class="list-icons d-inline-flex">
													<div class="list-icons-item dropdown">
														<a href="#" class="list-icons-item dropdown-toggle" data-toggle="dropdown"><i class="fa fa-file-text"></i></a>
														<div class="dropdown-menu dropdown-menu-right">
															<a href="#" class="dropdown-item" id = "purchase_edit" data-url = "{% url 'purchase_update' purchase.id %}"><i class="fa fa-pencil"></i> Edit</a>
															<a href="{% url 'purchase_approved' purchase.id %}" class="dropdown-item"><i class="mdi mdi-check"></i> Approved</a>
															<a href="{% url 'purchase_delete' purchase.id %}" class="dropdown-item"><i class="fa fa-remove"></i> Remove</a>
														</div>
													</div>
												</div>
											</td>
										</tr>

										{% endfor %}



									</tbody>
								</table>

							</div>
						</div>
					</div>
				</div>
			</div>
		  <!-- /.row -->

		</section>

  <div id="editcontainer"></div>

      {% else %}

  <div class="col-sm-6" style="margin-top: 30px">
	<div class="alert alert-danger">
	  <strong>Permission Denied!</strong> You do not have access this section.
	</div>
  </div>

  {% endif %}

{% endblock %}